spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
